/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTarefasRouteImport } from './routes/_dashboard.tarefas'
import { Route as DashboardRankingRouteImport } from './routes/_dashboard.ranking'
import { Route as DashboardPlaybookRouteImport } from './routes/_dashboard.playbook'
import { Route as DashboardPipelineRouteImport } from './routes/_dashboard.pipeline'
import { Route as DashboardOnboardingRouteImport } from './routes/_dashboard.onboarding'
import { Route as DashboardMetasRouteImport } from './routes/_dashboard.metas'
import { Route as DashboardLouRouteImport } from './routes/_dashboard.lou'
import { Route as DashboardLizRouteImport } from './routes/_dashboard.liz'
import { Route as DashboardLeadsRouteImport } from './routes/_dashboard.leads'
import { Route as DashboardFinanceirosRouteImport } from './routes/_dashboard.financeiros'
import { Route as DashboardFaturamentoRouteImport } from './routes/_dashboard.faturamento'
import { Route as DashboardEquipeRouteImport } from './routes/_dashboard.equipe'
import { Route as DashboardCursosRouteImport } from './routes/_dashboard.cursos'
import { Route as DashboardConversasRouteImport } from './routes/_dashboard.conversas'
import { Route as DashboardConfiguracoesRouteImport } from './routes/_dashboard.configuracoes'
import { Route as DashboardChatRouteImport } from './routes/_dashboard.chat'
import { Route as DashboardCentralRouteImport } from './routes/_dashboard.central'
import { Route as DashboardAlertasRouteImport } from './routes/_dashboard.alertas'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTarefasRoute = DashboardTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRankingRoute = DashboardRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaybookRoute = DashboardPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPipelineRoute = DashboardPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMetasRoute = DashboardMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLouRoute = DashboardLouRouteImport.update({
  id: '/lou',
  path: '/lou',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLizRoute = DashboardLizRouteImport.update({
  id: '/liz',
  path: '/liz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceirosRoute = DashboardFinanceirosRouteImport.update({
  id: '/financeiros',
  path: '/financeiros',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFaturamentoRoute = DashboardFaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipeRoute = DashboardEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCursosRoute = DashboardCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversasRoute = DashboardConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCentralRoute = DashboardCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertasRoute = DashboardAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof DashboardAlertasRoute
  '/central': typeof DashboardCentralRoute
  '/chat': typeof DashboardChatRoute
  '/configuracoes': typeof DashboardConfiguracoesRoute
  '/conversas': typeof DashboardConversasRoute
  '/cursos': typeof DashboardCursosRoute
  '/equipe': typeof DashboardEquipeRoute
  '/faturamento': typeof DashboardFaturamentoRoute
  '/financeiros': typeof DashboardFinanceirosRoute
  '/leads': typeof DashboardLeadsRoute
  '/liz': typeof DashboardLizRoute
  '/lou': typeof DashboardLouRoute
  '/metas': typeof DashboardMetasRoute
  '/onboarding': typeof DashboardOnboardingRoute
  '/pipeline': typeof DashboardPipelineRoute
  '/playbook': typeof DashboardPlaybookRoute
  '/ranking': typeof DashboardRankingRoute
  '/tarefas': typeof DashboardTarefasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof DashboardAlertasRoute
  '/central': typeof DashboardCentralRoute
  '/chat': typeof DashboardChatRoute
  '/configuracoes': typeof DashboardConfiguracoesRoute
  '/conversas': typeof DashboardConversasRoute
  '/cursos': typeof DashboardCursosRoute
  '/equipe': typeof DashboardEquipeRoute
  '/faturamento': typeof DashboardFaturamentoRoute
  '/financeiros': typeof DashboardFinanceirosRoute
  '/leads': typeof DashboardLeadsRoute
  '/liz': typeof DashboardLizRoute
  '/lou': typeof DashboardLouRoute
  '/metas': typeof DashboardMetasRoute
  '/onboarding': typeof DashboardOnboardingRoute
  '/pipeline': typeof DashboardPipelineRoute
  '/playbook': typeof DashboardPlaybookRoute
  '/ranking': typeof DashboardRankingRoute
  '/tarefas': typeof DashboardTarefasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/alertas': typeof DashboardAlertasRoute
  '/_dashboard/central': typeof DashboardCentralRoute
  '/_dashboard/chat': typeof DashboardChatRoute
  '/_dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/_dashboard/conversas': typeof DashboardConversasRoute
  '/_dashboard/cursos': typeof DashboardCursosRoute
  '/_dashboard/equipe': typeof DashboardEquipeRoute
  '/_dashboard/faturamento': typeof DashboardFaturamentoRoute
  '/_dashboard/financeiros': typeof DashboardFinanceirosRoute
  '/_dashboard/leads': typeof DashboardLeadsRoute
  '/_dashboard/liz': typeof DashboardLizRoute
  '/_dashboard/lou': typeof DashboardLouRoute
  '/_dashboard/metas': typeof DashboardMetasRoute
  '/_dashboard/onboarding': typeof DashboardOnboardingRoute
  '/_dashboard/pipeline': typeof DashboardPipelineRoute
  '/_dashboard/playbook': typeof DashboardPlaybookRoute
  '/_dashboard/ranking': typeof DashboardRankingRoute
  '/_dashboard/tarefas': typeof DashboardTarefasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/central'
    | '/chat'
    | '/configuracoes'
    | '/conversas'
    | '/cursos'
    | '/equipe'
    | '/faturamento'
    | '/financeiros'
    | '/leads'
    | '/liz'
    | '/lou'
    | '/metas'
    | '/onboarding'
    | '/pipeline'
    | '/playbook'
    | '/ranking'
    | '/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/central'
    | '/chat'
    | '/configuracoes'
    | '/conversas'
    | '/cursos'
    | '/equipe'
    | '/faturamento'
    | '/financeiros'
    | '/leads'
    | '/liz'
    | '/lou'
    | '/metas'
    | '/onboarding'
    | '/pipeline'
    | '/playbook'
    | '/ranking'
    | '/tarefas'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/alertas'
    | '/_dashboard/central'
    | '/_dashboard/chat'
    | '/_dashboard/configuracoes'
    | '/_dashboard/conversas'
    | '/_dashboard/cursos'
    | '/_dashboard/equipe'
    | '/_dashboard/faturamento'
    | '/_dashboard/financeiros'
    | '/_dashboard/leads'
    | '/_dashboard/liz'
    | '/_dashboard/lou'
    | '/_dashboard/metas'
    | '/_dashboard/onboarding'
    | '/_dashboard/pipeline'
    | '/_dashboard/playbook'
    | '/_dashboard/ranking'
    | '/_dashboard/tarefas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/tarefas': {
      id: '/_dashboard/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof DashboardTarefasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ranking': {
      id: '/_dashboard/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof DashboardRankingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/playbook': {
      id: '/_dashboard/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof DashboardPlaybookRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pipeline': {
      id: '/_dashboard/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof DashboardPipelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/onboarding': {
      id: '/_dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/metas': {
      id: '/_dashboard/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof DashboardMetasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/lou': {
      id: '/_dashboard/lou'
      path: '/lou'
      fullPath: '/lou'
      preLoaderRoute: typeof DashboardLouRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/liz': {
      id: '/_dashboard/liz'
      path: '/liz'
      fullPath: '/liz'
      preLoaderRoute: typeof DashboardLizRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads': {
      id: '/_dashboard/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/financeiros': {
      id: '/_dashboard/financeiros'
      path: '/financeiros'
      fullPath: '/financeiros'
      preLoaderRoute: typeof DashboardFinanceirosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/faturamento': {
      id: '/_dashboard/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof DashboardFaturamentoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/equipe': {
      id: '/_dashboard/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof DashboardEquipeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cursos': {
      id: '/_dashboard/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof DashboardCursosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/conversas': {
      id: '/_dashboard/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof DashboardConversasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/configuracoes': {
      id: '/_dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/chat': {
      id: '/_dashboard/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/central': {
      id: '/_dashboard/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof DashboardCentralRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alertas': {
      id: '/_dashboard/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof DashboardAlertasRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertasRoute: typeof DashboardAlertasRoute
  DashboardCentralRoute: typeof DashboardCentralRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardConversasRoute: typeof DashboardConversasRoute
  DashboardCursosRoute: typeof DashboardCursosRoute
  DashboardEquipeRoute: typeof DashboardEquipeRoute
  DashboardFaturamentoRoute: typeof DashboardFaturamentoRoute
  DashboardFinanceirosRoute: typeof DashboardFinanceirosRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLizRoute: typeof DashboardLizRoute
  DashboardLouRoute: typeof DashboardLouRoute
  DashboardMetasRoute: typeof DashboardMetasRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardPipelineRoute: typeof DashboardPipelineRoute
  DashboardPlaybookRoute: typeof DashboardPlaybookRoute
  DashboardRankingRoute: typeof DashboardRankingRoute
  DashboardTarefasRoute: typeof DashboardTarefasRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertasRoute: DashboardAlertasRoute,
  DashboardCentralRoute: DashboardCentralRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardConversasRoute: DashboardConversasRoute,
  DashboardCursosRoute: DashboardCursosRoute,
  DashboardEquipeRoute: DashboardEquipeRoute,
  DashboardFaturamentoRoute: DashboardFaturamentoRoute,
  DashboardFinanceirosRoute: DashboardFinanceirosRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLizRoute: DashboardLizRoute,
  DashboardLouRoute: DashboardLouRoute,
  DashboardMetasRoute: DashboardMetasRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardPipelineRoute: DashboardPipelineRoute,
  DashboardPlaybookRoute: DashboardPlaybookRoute,
  DashboardRankingRoute: DashboardRankingRoute,
  DashboardTarefasRoute: DashboardTarefasRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
